config/routes.rb
Project1::Application.routes.draw do

   root :to => 'welcome#index'

get 'test_page' => 'test#index'
get 'apples/:id' => 'apples#show'
match 'plural' => 'plural#show'
get 'apples/rot/:id' => 'apples#rot', :as => 'rot_apple'
match 'palindrome' => 'palindrome#show'
match 'addapple' => 'addapple#show'
get 'blog/:id' => 'blog#show'
match 'addblog' => 'addblog#show'
get 'shop/:id' => 'shop#show'
match 'addshop' => 'addshop#show'
match 'addorder' => 'addorder#show'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  attr_accessible :password
end

app/models/apple.rb
class Apple < ActiveRecord::Base
  attr_accessible :name, :tasty

  def rot
    self.tasty = false
    save
  end
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  attr_accessible :date, :entry, :name
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :address, :name, :postnr, :postort, :price
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  attr_accessible :desc, :img, :name, :price, :stock
end

app/controllers/addapple_controller.rb
class AddappleController < ApplicationController

def show
	@page_title = "Add a apple!"
    @id = params[:applename]
    @id_tasty = params[:tasty]
    if @id == nil
    	@apple_info = " "
    else
		# add to db stuff
			a = Apple.new
			a.tasty = @id_tasty
			a.name = @id
			a.save
			@apple_id = a.id
		
		# show stuff
			@apple_info = " hi"
    end
end

end

app/controllers/addblog_controller.rb
class AddblogController < ApplicationController

def show
@apple_info = " "
@password = params[:password]
@password_db = Admin.first.password
if @password == nil
	@apple_info = "No password"
else
if Digest::SHA256.hexdigest(@password) == @password_db
	# get the time, and make it look nice, could probably be done better :)
time = Time.new
if time.wday == 0
		dayofname = "Sunday"
	elsif time.wday == 1
		dayofname = "Monday"
	elsif time.wday == 2
		dayofname = "Tuesday"
	elsif time.wday == 3
		dayofname = "Wednesday"
	elsif time.wday == 4
		dayofname = "Thursday"
	elsif time.wday == 5
		dayofname = "Friday"
	elsif time.wday == 6
		dayofname = "Saturday"
end
# nice output stuff, probably easier way to do this
if time.month < 10
	month = "0#{time.month}"
else
	month = time.month
end
if time.day < 10
	day = "0#{time.day}"
else
	day = time.day
end
if time.hour < 10
	hour = "0#{time.hour}"
else
	hour = time.hour
end
if time.min < 10
	min = "0#{time.min}"
else 
	min = time.min
end
# output date
@id_date =  "#{dayofname}" + ", " + "#{time.year}" + "-" + "#{month}" + "-" + "#{day}" + "  " + "#{hour}" + ":" + "#{min}"
	# blog entry name
    @id = params[:applename]
    @id_entry = params[:entry]
    if @id == nil
    	@apple_info = " "
    else
		# add to db stuff
			a = Blog.new
			a.entry = @id_entry
			a.name = @id
			a.date = "#{dayofname}" + ", " + "#{time.year}" + "-" + "#{month}" + "-" + "#{day}" + "  " + "#{hour}" + ":" + "#{min}"
			a.save
		
		# show stuff
			@apple_info = @id +  @id_entry + @id_date
    end
else
	@apple_info = "Wrong password idiot."
end
end
end

end

app/controllers/addorder_controller.rb
class AddorderController < ApplicationController

def show
@apple_info = "Line 4"
    @name = params[:name]
    @address = params[:address]
    @postort = params[:postort]
    @postnr = params[:postnr]
    @price = "2239" # set a real price here sometime 
    if @name == nil
    	@apple_info = "You didnt order anything."
    else
		# add to db stuff
			a = Order.new
			a.name = @name
			a.address = @address
			a.postort = @postort
			a.postnr = @postnr
			a.price = @price
			a.save
		
		# show stuff
		@apple_info = "Order processed"
			# @apple_info = @item_name + @item_desc + @item_img + @item_stock + @item_price
    end
end

end

app/controllers/addshop_controller.rb
class AddshopController < ApplicationController

def show
@apple_info = "Line 4"
@password = params[:password]
@password_db = Admin.first.password
if @password == nil
	@apple_info = "No password"
else
if Digest::SHA256.hexdigest(@password) == @password_db
	# blog entry name
    @item_name = params[:name]
    @item_desc = params[:desc]
    @item_img = params[:img]
    @item_stock = params[:stock]
    @item_price = params[:price]
    if @item_name == nil
    	@apple_info = "Input info"
    else
		# add to db stuff
			a = Shop.new
			a.name = @item_name
			a.desc = @item_desc
			a.img = @item_img
			a.stock = @item_stock
			a.price = @item_price
			a.save
		
		# show stuff
		@apple_info = "Worked"
			# @apple_info = @item_name + @item_desc + @item_img + @item_stock + @item_price
    end
else
	@apple_info = "Wrong password"
end
end
end

end

app/controllers/apples_controller.rb
class ApplesController < ApplicationController
 
  def show
    id = params[:id]
    @apple = Apple.find(id)
  end
  
  def rot
    id = params[:id]
    @apple = Apple.find(id)
    @apple.rot
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
 
  def show
    id = params[:id]
    @blog = Blog.find(id)
  end
  
end

app/controllers/palindrome_controller.rb
class PalindromeController < ApplicationController

def show
    @id = params[:comments]
	if @id == nil
		@font_color = "black"
		@reply = "Set a word in the box, and click the button!"
	elsif @id == @id.reverse
		@font_color = "lime"
		@reply = @id + ", is a palindrome!"
	else
		@font_color = "red"
    		@reply = @id +", is NOT a palindrome :("
    	end	
end

end

app/controllers/plural_controller.rb
class PluralController < ApplicationController

def show
    @id = params[:comments]
	if @id == nil
		@reply = "Set a word in the box, and click the button!"
	else
    		@reply = @id +  " in plural is " +  @id.pluralize + '.'
    	end	
end

end

app/controllers/shop_controller.rb
# shop controller

class ShopController < ApplicationController
 
  def show
    id = params[:id]
    @item = Shop.find(id)
  end
  
end

app/controllers/test_controller.rb
class TestController < ApplicationController
 
  def index
    @message = "i like text"
    @message2 = "git is cool"
    @message3 = "smb is cool"
    @message4 = "git works?"
    @message5 = "dropbox folder sync works!"
  end
 
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
 
  def index
    @message1 = RUBY_VERSION
  end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/addblog/show.html.erb
<html>
<h1>Add a blog entry to the database</h1>
<form name="input" method=POST>
Name of Blog entry: <input type="text" name="applename"><br>
<br>
<br>
<textarea name="entry" cols="40" rows="5">
Enter your Text here...
</textarea><br><br>
Password: <input type="password" name="password">
<input type="submit" value="Add Blog Entry!">
</form>
<p><%= @apple_info %></p>
</html>

app/views/addorder/show.html.erb
<html>
<h1>Order mottagning</h1>
<form name="input" method=POST>
Namn: <input type="text" name="name"><br>
<br>
Addres (Gata Nr, t.ex. ABCgatan 10): <input type="text" name="address"><br>
Postort: <input type="text" name="postort"><br>
Postnr: <input type="text" name="postnr"><br>
<input type="submit" value="Beställ">
</form>
<p><%= @apple_info %></p>
</html>

app/views/addshop/show.html.erb
<html>
<h1>Lägg till ett objekt i databasen</h1>
<form name="input" method=POST>
Produktnamn: <input type="text" name="name"><br>
<br>
Bildlänk: <input type="text" name="img"><br>
Hur många finns i lager (nummer endast): <input type="text" name="stock"><br>
Önskat pris: <input type="text" name="price"><br>
<textarea name="desc" cols="40" rows="5">
Objekt beskivning här...
</textarea><br><br>
Bekräfta med lösenord: <input type="password" name="password">
<input type="submit" value="Spara">
</form>
<p><%= @apple_info %></p>
</html>

app/views/apples/rot.html.erb
<% if @apple.tasty? %>
  <p>something is wrong i guess</p>
<% else %>
  <p>you rotted the apple</p>
<% end %>

app/views/apples/show.html.erb
<h1>Apple <%= @apple.id %></h1>
 
<p>Name: <%= @apple.name %></p>
<p>Tasty: <%= @apple.tasty? %></p>

<% if @apple.tasty? %>
  <%= link_to 'Rot this apple', rot_apple_path %>
<% end %>

app/views/blog/show.html.erb
<p>Blog id <%= @blog.id %></p>
 <h2><%= @blog.name %></h2>
<p><u><%= @blog.date %></p></u>
<p><%= @blog.entry %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= @page_title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/palindrome/show.html.erb
<html>
<h1>Palindrome</h1>
<form name="input">
<input type="text" name="comments">
<input type="submit" value="Palindrome?">
</form>
</body>
<h1><font color="<%= @font_color %>"><%= @reply %></h1></font>
</html>


app/views/plural/show.html.erb
<html>
<h1>Plural</h1>
<form name="input">
<input type="text" name="comments">
<input type="submit" value="Pluralize!">
</form>
</body>
<h1><%= @reply %></h1>
</html>

app/views/shop/show.html.erb
<p>Item id <%= @item.id %><br>
	Namn <%= @item.name %><br>
	<img src="<%= @item.img %>"><br>
	Beskrivning: <%= @item.desc %><br>
	I lager: <%= @item.stock %><br>
	<h3><font color="red"><%= @item.price %><br>
		

app/views/welcome/index.html.erb
Ruby version: <%= @message1 %>
<br>
<%=link_to "Pluralizer", "/plural" %>
<%=link_to "Apples", "/apples" %>
<%=link_to "Test page", "/test_page" %>
<%=link_to "Palindrome", "/palindrome" %>
<%=link_to "Add a apple", "/addapple" %>
